# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_rule.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog.resize(300, 100)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(300, 100))
        Dialog.setMaximumSize(QtCore.QSize(300, 100))
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_folder = QtWidgets.QLabel(Dialog)
        self.label_folder.setObjectName("label_folder")
        self.gridLayout.addWidget(self.label_folder, 0, 0, 1, 1)
        self.label_folder_value = ClickableLabel(Dialog)
        self.label_folder_value.setObjectName("label_folder_value")
        self.gridLayout.addWidget(self.label_folder_value, 0, 1, 1, 1)
        self.label_app = QtWidgets.QLabel(Dialog)
        self.label_app.setObjectName("label_app")
        self.gridLayout.addWidget(self.label_app, 1, 0, 1, 1)
        self.label_app_value = ClickableLabel(Dialog)
        self.label_app_value.setObjectName("label_app_value")
        self.gridLayout.addWidget(self.label_app_value, 1, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 2)
        self.pushButton_confirm = QtWidgets.QPushButton(Dialog)
        self.pushButton_confirm.setObjectName("pushButton_confirm")
        self.gridLayout_2.addWidget(self.pushButton_confirm, 1, 0, 1, 1)
        self.pushButton_cancel = QtWidgets.QPushButton(Dialog)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.gridLayout_2.addWidget(self.pushButton_cancel, 1, 1, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Manage rules"))
        self.label_folder.setText(_translate("Dialog", "Folder"))
        self.label_folder_value.setText(_translate("Dialog", "TextLabel"))
        self.label_app.setText(_translate("Dialog", "Application"))
        self.label_app_value.setText(_translate("Dialog", "TextLabel"))
        self.pushButton_confirm.setText(_translate("Dialog", "Confirm"))
        self.pushButton_cancel.setText(_translate("Dialog", "Cancel"))


from ui.util.ClickableLabel import ClickableLabel
